In [1]:
import numpy as np

a = np.array([1, 2, 3, 4])
print(a) 

[1 2 3 4]


In [2]:
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a, b)
toc = time.time()

print(c)
print("Vectorized version:" + str(1000 * (toc - tic)) + "ms")

c = 0
tic = time.time()
for i in range(1000000):
    c += a[i] * b[i]
toc = time.time()

print(c)
print("For loop:" + str(1000 * (toc - tic)) + "ms")

249842.97730221902
Vectorized version:3.020048141479492ms
249842.97730222912
For loop:438.9791488647461ms


In [3]:
A = np.array([[56.0, 0.0, 4.4, 68.0],
            [1.2, 104.0, 52.0, 8.0],
            [1.8, 135.0, 99.0, 0.9]])

In [4]:
cal = A.sum(axis = 0)
print(cal)

[ 59.  239.  155.4  76.9]


In [5]:
percentage = 100 * A/cal.reshape(1, 4)
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [6]:
a = np.random.randn(5)

In [7]:
print(a)

[-1.2088784  -0.71599644  0.2654659  -0.13318766  0.66019608]


In [8]:
print(a.shape)

(5,)


In [9]:
print(a.T)

[-1.2088784  -0.71599644  0.2654659  -0.13318766  0.66019608]


In [10]:
print(np.dot(a, a.T))

2.4981078607417593


In [11]:
a = np.random.randn(5, 1)
print(a)
print(a.T)
print(np.dot(a.T, a))
print(np.dot(a, a.T))

[[-0.96354047]
 [ 0.5136295 ]
 [-0.27568617]
 [ 0.4388373 ]
 [ 1.32617316]]
[[-0.96354047  0.5136295  -0.27568617  0.4388373   1.32617316]]
[[3.21954179]]
[[ 0.92841024 -0.49490281  0.26563478 -0.4228375  -1.27782151]
 [-0.49490281  0.26381526 -0.14160055  0.22539978  0.68116166]
 [ 0.26563478 -0.14160055  0.07600286 -0.12098137 -0.3656076 ]
 [-0.4228375   0.22539978 -0.12098137  0.19257818  0.58197425]
 [-1.27782151  0.68116166 -0.3656076   0.58197425  1.75873524]]
